// Trechos reais de respostas de https://api.dicionario-aberto.net/word/{palavra}

export const CASA_XML = [
  '<entry id="casa">',
  '<form>',
  '<orth>Casa</orth>',
  '</form>',
  '<sense>',
  '<gramGrp>f.</gramGrp>',
  '<def>',
  'Edifício para habitação: _uma casa moderna_.',
  'Morada, moradia, vivenda: _vou para minha casa_.',
  '</def>',
  '</sense>',
  '<sense ast="1">',
  '<def>',
  '_Casa de saúde_, hospital particular, em que os doentes pagam o tratamento.',
  '</def>',
  '</sense>',
  '<etym orig="Lat">(Lat. _casa_)</etym>',
  '</entry>',
].join('\n');

export const CAFE_XML = [
  '<entry id="café">',
  '<form>',
  '<orth>Café</orth>',
  '</form>',
  '<sense>',
  '<gramGrp>m.</gramGrp>',
  '<def>',
  'Semente de cafezeiro.',
  'Infusão dessa semente, depois de torrada e moída.',
  '</def>',
  '</sense>',
  '<sense ast="1">',
  '<usg type="style">Gír.</usg>',
  '<def>',
  '_Café frio_, xícara de vinho.',
  '</def>',
  '</sense>',
  '<etym orig="ár">(Do ár. _cahua_)</etym>',
  '</entry>',
].join('\r\n');

export const MANGA_XML = [
  '<entry n="1" id="manga:1" type="hom">',
  '<form>',
  '<orth>Manga</orth>',
  '</form>',
  '<sense>',
  '<gramGrp>f.</gramGrp>',
  '<def>',
  'Filtro afunilado, para líquidos.',
  'Mangueira^2.',
  '</def>',
  '</sense>',
  '</entry>',
].join('\n');
